In [ ]:
# Tracking Data Inspector and Filter for Houdini
# This notebook helps analyze and filter JSON tracking data

import json
import os
import ipywidgets as widgets
from IPython.display import display, clear_output
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime
import pandas as pd

In [6]:
import pandas as pd
# Load the parquet file
tracking_df = pd.read_parquet('/media/M2_disk/roger/sonar/YOLO-3D/videos/out/Baquetes_tracking_data.parquet')

# Display information about the dataframe
print(f"Dataframe shape: {tracking_df.shape}")

# Display the column names
print("\nColumns in the dataframe:")
print(tracking_df.columns.tolist())

# Show the first few rows of the dataframe
print("\nSample data:")
tracking_df = tracking_df[tracking_df.frame == 50]
tracking_df.head(100)

Dataframe shape: (319556, 16)

Columns in the dataframe:
['frame', 'timestamp', 'object_id', 'class', 'keypoint_index', 'x', 'y', 'depth', 'confidence', 'spatial_spread', 'avg_distance', 'formation_area', 'symmetry_score', 'num_performers', 'distance', 'distance_to_com']

Sample data:

,frame,timestamp,object_id,class,keypoint_index,x,y,depth,confidence,spatial_spread,avg_distance,formation_area,symmetry_score,num_performers,distance,distance_to_com
2745,50,7.21724,-100.0,center_of_mass,-1,931.230908,265.197388,0.348290,1.000000,283.082453,1056.51253,202311.096723,0.211543,3.0,NaN,NaN
2746,50,7.21724,-200.0,performer_connection,-1,1.000000,3.000000,0.000000,1.000000,NaN,NaN,NaN,NaN,NaN,1541.250402,NaN
2747,50,7.21724,-200.0,performer_connection,-1,1.000000,4.000000,0.000000,1.000000,NaN,NaN,NaN,NaN,NaN,794.418917,NaN
2748,50,7.21724,-200.0,performer_connection,-1,3.000000,4.000000,0.000000,1.000000,NaN,NaN,NaN,NaN,NaN,833.868272,NaN
2749,50,7.21724,1.0,person,0,391.589081,-101.886658,0.247059,0.792253,NaN,NaN,NaN,NaN,NaN,NaN,652.659180
2750,50,7.21724,1.0,person,1,392.984619,-114.747253,0.243137,0.591186,NaN,NaN,NaN,NaN,NaN,NaN,658.837617
2751,50,7.21724,1.0,person,2,404.353943,-107.198914,0.239216,0.800790,NaN,NaN,NaN,NaN,NaN,NaN,645.196366
2752,50,7.21724,1.0,person,3,0.000000,727.103394,NaN,0.312741,NaN,NaN,NaN,NaN,NaN,NaN,1039.494188
2753,50,7.21724,1.0,person,4,396.824280,-83.774902,0.243137,0.725392,NaN,NaN,NaN,NaN,NaN,NaN,638.257089
2754,50,7.21724,1.0,person,5,353.356781,4.461853,0.301961,0.972288,NaN,NaN,NaN,NaN,NaN,NaN,633.972812
2755,50,7.21724,1.0,person,6,336.685089,33.739380,0.309804,0.978386,NaN,NaN,NaN,NaN,NaN,NaN,638.010611
2756,50,7.21724,1.0,person,7,313.282166,102.562866,0.294118,0.936964,NaN,NaN,NaN,NaN,NaN,NaN,638.991892
2757,50,7.21724,1.0,person,8,344.689880,150.265625,0.254902,0.956342,NaN,NaN,NaN,NaN,NaN,NaN,597.695320
2758,50,7.21724,1.0,person,9,375.670105,193.585266,0.254902,0.953116,NaN,NaN,NaN,NaN,NaN,NaN,560.157219
2759,50,7.21724,1.0,person,10,386.246979,227.631348,0.231373,0.965906,NaN,NaN,NaN,NaN,NaN,NaN,546.277131
2760,50,7.21724,1.0,person,11,228.334045,269.759674,0.309804,0.990068,NaN,NaN,NaN,NaN,NaN,NaN,702.911670
2761,50,7.21724,1.0,person,12,220.940323,283.482361,0.301961,0.988796,NaN,NaN,NaN,NaN,NaN,NaN,710.525903
2762,50,7.21724,1.0,person,13,292.859009,401.225647,0.298039,0.992601,NaN,NaN,NaN,NaN,NaN,NaN,652.703894
2763,50,7.21724,1.0,person,14,291.812225,421.120789,0.305882,0.991555,NaN,NaN,NaN,NaN,NaN,NaN,658.155272
2764,50,7.21724,1.0,person,15,246.853180,523.728394,0.345098,0.994378,NaN,NaN,NaN,NaN,NaN,NaN,731.581284
2765,50,7.21724,1.0,person,16,329.920685,537.351929,0.294118,0.993424,NaN,NaN,NaN,NaN,NaN,NaN,660.031882
2766,50,7.21724,3.0,person,0,0.000000,727.103394,NaN,0.164024,NaN,NaN,NaN,NaN,NaN,NaN,1039.494188
2767,50,7.21724,3.0,person,1,0.000000,727.103394,NaN,0.083588,NaN,NaN,NaN,NaN,NaN,NaN,1039.494188
2768,50,7.21724,3.0,person,2,0.000000,727.103394,NaN,0.062833,NaN,NaN,NaN,NaN,NaN,NaN,1039.494188
2769,50,7.21724,3.0,person,3,0.000000,727.103394,NaN,0.087821,NaN,NaN,NaN,NaN,NaN,NaN,1039.494188
2770,50,7.21724,3.0,person,4,0.000000,727.103394,NaN,0.063470,NaN,NaN,NaN,NaN,NaN,NaN,1039.494188
2771,50,7.21724,3.0,person,5,1803.565674,201.327637,0.878431,0.665533,NaN,NaN,NaN,NaN,NaN,NaN,874.669977
2772,50,7.21724,3.0,person,6,1788.501953,118.041138,0.925490,0.613669,NaN,NaN,NaN,NaN,NaN,NaN,869.809714
2773,50,7.21724,3.0,person,7,1603.166260,337.973328,0.647059,0.730340,NaN,NaN,NaN,NaN,NaN,NaN,675.865034
2774,50,7.21724,3.0,person,8,0.000000,727.103394,NaN,0.429012,NaN,NaN,NaN,NaN,NaN,NaN,1039.494188
2775,50,7.21724,3.0,person,9,1636.917480,645.261475,0.454902,0.779278,NaN,NaN,NaN,NaN,NaN,NaN,801.524961
2776,50,7.21724,3.0,person,10,1550.222656,-16.888367,0.643137,0.567740,NaN,NaN,NaN,NaN,NaN,NaN,680.237636
2777,50,7.21724,3.0,person,11,1746.748901,-12.646912,0.949020,0.704944,NaN,NaN,NaN,NaN,NaN,NaN,861.549424
2778,50,7.21724,3.0,person,12,1723.186157,-48.455078,0.937255,0.590624,NaN,NaN,NaN,NaN,NaN,NaN,851.804748
2779,50,7.21724,3.0,person,13,1758.224487,391.344116,0.145098,0.644908,NaN,NaN,NaN,NaN,NaN,NaN,836.559274
2780,50,7.21724,3.0,person,14,0.000000,727.103394,NaN,0.474763,NaN,NaN,NaN,NaN,NaN,NaN,1039.494188
2781,50,7.21724,3.0,person,15,1745.718750,706.797485,0.749020,0.835827,NaN,NaN,NaN,NaN,NaN,NaN,926.499448
2782,50,7.21724,3.0,person,16,1689.775635,692.056335,0.733333,0.757181,NaN,NaN,NaN,NaN,NaN,NaN,870.401518
2783,50,7.21724,4.0,person,0,1066.644043,241.634338,0.196078,0.812655,NaN,NaN,NaN,NaN,NaN,NaN,137.448017
2784,50,7.21724,4.0,person,1,1071.178955,235.457886,0.203922,0.635477,NaN,NaN,NaN,NaN,NaN,NaN,143.073108
2785,50,7.21724,4.0,person,2,1077.103271,245.596527,0.203922,0.677428,NaN,NaN,NaN,NaN,NaN,NaN,147.183425
2786,50,7.21724,4.0,person,3,1069.509766,226.706787,0.200000,0.726791,NaN,NaN,NaN,NaN,NaN,NaN,143.536024
2787,50,7.21724,4.0,person,4,1098.887695,252.937408,0.211765,0.752846,NaN,NaN,NaN,NaN,NaN,NaN,168.104503
2788,50,7.21724,4.0,person,5,1033.880737,253.159058,0.172549,0.991999,NaN,NaN,NaN,NaN,NaN,NaN,103.353469
2789,50,7.21724,4.0,person,6,1102.745850,303.448242,0.203922,0.996199,NaN,NaN,NaN,NaN,NaN,NaN,175.728552
2790,50,7.21724,4.0,person,7,974.301514,224.910828,0.129412,0.963694,NaN,NaN,NaN,NaN,NaN,NaN,58.975686
2791,50,7.21724,4.0,person,8,1152.330566,370.475525,0.211765,0.985017,NaN,NaN,NaN,NaN,NaN,NaN,244.884799
2792,50,7.21724,4.0,person,9,957.690491,197.625366,0.109804,0.934772,NaN,NaN,NaN,NaN,NaN,NaN,72.568201
2793,50,7.21724,4.0,person,10,1178.333496,441.264465,0.235294,0.965263,NaN,NaN,NaN,NaN,NaN,NaN,303.412787
2794,50,7.21724,4.0,person,11,991.438477,372.654175,0.192157,0.994936,NaN,NaN,NaN,NaN,NaN,NaN,123.174420
2795,50,7.21724,4.0,person,12,1031.969727,396.245667,0.211765,0.995729,NaN,NaN,NaN,NaN,NaN,NaN,165.293620
2796,50,7.21724,4.0,person,13,974.303467,416.160339,0.231373,0.985380,NaN,NaN,NaN,NaN,NaN,NaN,156.987494
2797,50,7.21724,4.0,person,14,1013.315735,437.411194,0.231373,0.986821,NaN,NaN,NaN,NaN,NaN,NaN,190.776123
2798,50,7.21724,4.0,person,15,925.787231,507.378418,0.235294,0.972515,NaN,NaN,NaN,NaN,NaN,NaN,242.242249
2799,50,7.21724,4.0,person,16,971.077698,524.302673,0.258824,0.974871,NaN,NaN,NaN,NaN,NaN,NaN,262.151357

In [1]:
import pandas as pd

# Load the parquet file
tracking_df = pd.read_parquet('/media/M2_disk/roger/sonar/YOLO-3D/videos/out/Baquetes_tracking_data.parquet')


# Save as CSV
tracking_df.to_csv('/media/M2_disk/roger/sonar/YOLO-3D/videos/out/Baquetes_tracking_data_frame.csv', index=False)

print("Saved filtered DataFrame as CSV.")

Saved filtered DataFrame as CSV.

In [2]:
tracking = pd.read_csv('/media/M2_disk/roger/sonar/YOLO-3D/videos/out/Baquetes_tracking_data_frame.csv')
tracking.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 426432 entries, 0 to 426431
Data columns (total 16 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   frame            426432 non-null  int64
 1   timestamp        426432 non-null  float64
 2   object_id        426432 non-null  int64
 3   class            426432 non-null  object
 4   keypoint_index   426432 non-null  int64
 5   x                426432 non-null  float64
 6   y                426432 non-null  float64
 7   depth            405108 non-null  float64
 8   confidence       426432 non-null  float64
 9   spatial_spread   4513 non-null    float64
 10  avg_distance     4513 non-null    float64
 11  formation_area   4513 non-null    float64
 12  symmetry_score   4513 non-null    float64
 13  num_performers   4513 non-null    float64
 14  distance         43873 non-null   float64
 15  distance_to_com  378046 non-null  float64
dtypes: float64(12), int64(3), object(1)
memory usage: 52.1+ MB

In [5]:
import pandas as pd
video = 'Suspiro'
# Load the parquet file
file_path = f'/media/M2_disk/roger/sonar/YOLO-3D/videos/out/{video}_tracking_data.parquet'
tracking_df = pd.read_parquet(file_path)

# Split the dataframe based on keypoint_index
keypoint_negative_df = tracking_df[tracking_df.keypoint_index == -1]
keypoint_positive_df = tracking_df[tracking_df.keypoint_index >= 0]
columns_to_remove = [
    'spatial_spread',
    'avg_distance',
    'formation_area',
    'symmetry_score',
    'num_performers',
    'distance'
]

keypoint_positive_df = keypoint_positive_df.drop(columns=columns_to_remove, errors='ignore')

# Define output file paths
negative_output_path = f'/media/M2_disk/roger/sonar/YOLO-3D/videos/out/{video}_company_metrics.csv'
positive_output_path = f'/media/M2_disk/roger/sonar/YOLO-3D/videos/out/{video}_tracking_data.csv'

# Save to CSV
keypoint_negative_df.to_csv(negative_output_path, index=False)
keypoint_positive_df.to_csv(positive_output_path, index=False)

# Print information about the split
print(f"Original dataframe: {tracking_df.shape[0]} rows")
print(f"Keypoint index -1: {keypoint_negative_df.shape[0]} rows saved to {negative_output_path}")
print(f"Keypoint index ≥0: {keypoint_positive_df.shape[0]} rows saved to {positive_output_path}")

Original dataframe: 316546 rows
Keypoint index -1: 36080 rows saved to /media/M2_disk/roger/sonar/YOLO-3D/videos/out/Suspiro_company_metrics.csv
Keypoint index ≥0: 280466 rows saved to /media/M2_disk/roger/sonar/YOLO-3D/videos/out/Suspiro_tracking_data.csv

In [8]:
keypoint_negative_df.head(10)

,frame,timestamp,object_id,class,keypoint_index,x,y,depth,confidence,spatial_spread,avg_distance,formation_area,symmetry_score,num_performers,distance,distance_to_com
0,0,1.595369,-100,center_of_mass,-1,694.184576,545.264671,0.345811,1.0,179.118989,601.634599,0.000000,0.201992,2.0,NaN,NaN
1,0,1.595369,-200,performer_connection,-1,1.000000,2.000000,0.000000,1.0,NaN,NaN,NaN,NaN,NaN,601.634599,NaN
70,3,2.210359,-100,center_of_mass,-1,1000.774249,583.992090,0.492941,1.0,158.107184,277.835165,0.000000,0.257962,2.0,NaN,NaN
71,3,2.210359,-200,performer_connection,-1,1.000000,3.000000,0.000000,1.0,NaN,NaN,NaN,NaN,NaN,277.835165,NaN
106,4,2.406228,-100,center_of_mass,-1,793.547710,565.697716,0.393137,1.0,138.329686,492.513842,102620.111356,0.290428,3.0,NaN,NaN
107,4,2.406228,-200,performer_connection,-1,1.000000,3.000000,0.000000,1.0,NaN,NaN,NaN,NaN,NaN,450.161767,NaN
108,4,2.406228,-200,performer_connection,-1,1.000000,2.000000,0.000000,1.0,NaN,NaN,NaN,NaN,NaN,549.335276,NaN
109,4,2.406228,-200,performer_connection,-1,3.000000,2.000000,0.000000,1.0,NaN,NaN,NaN,NaN,NaN,478.044483,NaN
161,5,2.613768,-100,center_of_mass,-1,764.722365,544.836538,0.320044,1.0,118.016183,498.876534,106141.953175,0.278768,3.0,NaN,NaN
162,5,2.613768,-200,performer_connection,-1,1.000000,3.000000,0.000000,1.0,NaN,NaN,NaN,NaN,NaN,467.869793,NaN

In [9]:
keypoint_positive_df.head(100)

,frame,timestamp,object_id,class,keypoint_index,x,y,depth,confidence,distance_to_com
2,0,1.595369,1,person,0,0.000000,0.000000,NaN,0.001525,882.726337
3,0,1.595369,1,person,1,0.000000,0.000000,NaN,0.000325,882.726337
4,0,1.595369,1,person,2,0.000000,0.000000,NaN,0.000967,882.726337
5,0,1.595369,1,person,3,0.000000,0.000000,NaN,0.000466,882.726337
6,0,1.595369,1,person,4,0.000000,0.000000,NaN,0.002091,882.726337
...,...,...,...,...,...,...,...,...,...,...
99,3,2.210359,3,person,10,0.000000,0.000000,NaN,0.024194,1158.704388
100,3,2.210359,3,person,11,1116.108887,629.255188,0.615686,0.626273,595.272085
101,3,2.210359,3,person,12,1066.158447,630.300903,0.635294,0.533373,587.640940
102,3,2.210359,3,person,13,1119.978394,757.032532,0.145098,0.940689,596.033984
103,3,2.210359,3,person,14,1051.886963,760.644470,0.635294,0.912583,586.224608